# Generated by Django 4.2.7 on 2024-01-10 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('e', 'Quick & Easy'), ('m', 'Some Prep'), ('h', 'Lots of prep or cook time.')], max_length=50)),
                ('directions', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_editted', models.DateField(auto_now=True)),
                ('reference_url', models.URLField()),
                ('rating', models.CharField(choices=[('1', 'Yum!'), ('2', 'Om nom nom!!'), ('3', 'Regrets!!!')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MeasuredIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(max_length=5)),
                ('unit', models.CharField(choices=[('tsp', 'tsp.'), ('tbsp', 'tbsp.'), ('cup', 'cup'), ('can', 'can'), ('oz', 'oz.'), ('lb', 'lb.')], max_length=50)),
                ('ingredient', models.ManyToManyField(to='recipe_app.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_app.recipe')),
            ],
        ),
    ]
